site_name: SEEREP Documentation
repo_url: https://github.com/agri-gaia/seerep
nav:
  - Home: index.md
  - Getting started:
    - Installation: installation.md
    - Package Overview: packages.md
    - Docs: docs.md
    - Tests: testing.md
  - Tutorials:
    - Python: 'tutorials-python.md'
    - C++: 'tutorials-c++.md'

theme:
  name: material
  language: en
  theme:
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - meta
  - attr_list
